import os

version = "0_03"

env=Environment()
env.Append(CXXFLAGS = "-std=c++11")

libraries = ["SDL2", "libHoney.a"]

env.AppendUnique(FRAMEWORKS = Split("OpenGL"))

BearsLoveHoney = env.Program(target = "BearsLoveHoney",
  source = Glob("./Source/*.cpp"),
  LIBS = libraries,
  LIBPATH="../Engine/Build/%s/Library" % version,
  CPPPATH="../Engine/Build/%s/Includes" % version)

Default()

def cleanObjects(target, source, env):
  os.system("rm ./Source/*.o")

cleanup = Command("cleanObjects", [], cleanObjects)
Depends(cleanup, BUILD_TARGETS)
BUILD_TARGETS.append("cleanObjects")