import os

honey_version = "0_25"

env=Environment()
env.Append(CXXFLAGS = "-std=c++11")

libraries = ["libHoney.a", "boost_filesystem-mt", "boost_system-mt"]

env.AppendUnique(FRAMEWORKS = Split("OpenGL SDL2 SDL2_image SDL2_mixer SDL2_ttf"))

DrawGrassField = env.Program(target = "DrawGrassField",
  source = Glob("./Source/*.cpp"),
  LIBS = libraries,
  LIBPATH="../../Engine/Build/%s/Library" % honey_version,
  CPPPATH="../../Engine/Build/%s/Includes" % honey_version)

Default()

def cleanObjects(target, source, env):
  os.system("rm ./Source/*.o")

cleanup = Command("cleanObjects", [], cleanObjects)
Depends(cleanup, BUILD_TARGETS)
#BUILD_TARGETS.append("cleanObjects")
