import os

version = "0_04"

env=Environment()
env.Append(CXXFLAGS = "-std=c++11")

os.system("rm -rf ./Build/%s" % version)
os.system("mkdir ./Build/%s" % version)
os.system("mkdir ./Build/%s/Library" % version)
os.system("mkdir ./Build/%s/Includes" % version)

BuildLibrary = env.StaticLibrary("Honey", Glob("./Source/*.cpp"))

def postBuildSteps(target, source, env):
  os.system("rm ./Source/*.o")
  os.system("mv libHoney.a ./Build/%s/Library/" % version)
  os.system("cp ./Source/*.h ./Build/%s/Includes" % version)
  os.system("cp -R ./Source/glm ./Build/%s/Includes" % version)

post = Command("postBuildSteps", [], postBuildSteps)
Depends(post, BuildLibrary)
BUILD_TARGETS.append("postBuildSteps")